
require("dotenv").config()

module.exports = {
    wrong_password: "Wrong Password",
    auth_failed:"Authentication Failed",
    something_wrong:"Something wrong",
    errorMessage :'Oops! Something went wrong here...',
    account_locked:"Account is locked due to multiple failed login attempts",
    account_unlocked:"Account has been unlocked successfully",
    invalid_credentials_attempts_remaining:"Invalid credentials. {attempts} attempts remaining before account lockout",
    invalid_captcha:"Invalid captcha verification. Please try again.",
    request_invalid:"Your request is not valid",
    mobile_num_invalid:"Mobile Number is not valid",
    mobile_num_exists:"Mobile No. already exists.",
    sipId_exists:"Sip Id already exists.",
    password_invalid:"Password must contain at least one letter, one number and one special character (!@#$%^&*)",
    enter_correct_password:"Please Enter correct Password",
    reset_password_link_sent_to_email:"Check your email for a reset link, if your account exists.",
    reset_password_success:"Reset password successfully",
    password_not_reset:"Password not able to reset",
    reset_token_already_used:"Reset token has already been used. Please request a new password reset.",
    reset_token_expired:"Reset token has expired. Please request a new password reset.",
    reset_token_invalid:"Invalid reset token. Please request a new password reset.",
    reset_rate_limit_exceeded:"Too many password reset requests. Please try again later.",
    enter_old_password:"Please enter correct/valid old password",
    password_change_success:"Password Changed Successfully",
    new_password_not_same_as_old_password:"New Password must not be same as old password",
    pincode_invalid:"Pincode is not valid",
    org_not_found:"Organisation not found",
    org_list_not_found:"Organisation list not found",
    org_list_get:"Organisation list get successfully",
    email_not_verified:"Email is not verified, Please verify your email",
    email_not_register:"Email is not registered, Please register",
    user_login_success:"User login successfully",
    user_not_login:"User not able to login",
    sub_scheme_create:"Sub-Scheme created Successfully",
    subScheme_exist:"Sub-Scheme already exist",
    subScheme_Code_exist:"Sub-Scheme code already exist",
    subScheme_Name_exist:"Sub-Scheme name already exist",
    user_profile_create:"User Profile created Successfully",
    user_profile_not_create:"User Profile not able to create",
    user_profile_already_create:"User Profile already created",
    user_profile_get:"User Profile get Successfully",
    jobe_role_create:"Job Role Created Successfully",
    jobe_role_not_create:"Job Role not Created!",
    sub_scheme_not_create:"Sub-scheme not Created",
    jobeRole_exist:"Job Role already exist",
    user_profile_update:"User Profile has been updated successfully",
    user_profile_not_created:"User profile is not created",
    create_user_profile:"Please create User profile",
    user_not_found:"User not found",
    user_not_active:"User is not in active state. Please contact admin",
    user_exist_already:"User already exists.",
    user_type_admin:"User type should be super admin",
    user_created:"User created Successfully",
    user_not_create:"User not able to create",
    user_role_invalid:"User Role is not valid",
    user_type_invalid:"User Type is not Valid",
    user_profile_list:'User profile list get successfully.',
    tour_viewed:"Tour successfully viewed",
    user_already_register:"User details you have entered already registered",
    client_profile_get:'Client profile get successfully',
    client_profile_create:"Client Profile created successfully",
    batch_create:"Batch created successfully",
    batch_assign:"Batch assign successfully",
    client_profile_update:"Client Profile updated successfully",
    client_profile_not_create:"Client profile not able to create",
    batch_not_create:"Batch ID already exists",
    assignBatch_not_find:"Batch list not found",
    client_profile_not_found:"Client Profile not found",
    client_profile_delete:"Client profile data delete successfully",
    client_status_change:"client status changed successfully",
    client_profile_approved_by_admin:"User Profile approved by admin successfully",
    state_get:"States get successfully",
    city_get:"cities get successfully",
    country_name_required:"country name required",
    state_not_found:"State Name not found",
    state_fips_required:"State fips code is required",
    accept_terms_invalid:"Accept Terms and condition is not valid",
    verify_your_email:"Please verify your email address",
    email_already_verified:"Email is already verified",
    email_verified:"Congratulations! Your email has been successfully verified",
    email_verify_to_login:"Please verify Email to login",
    token_missed:"Token is missing",
    token_invalid:"Token is not Valid",
    token_required:"Token is required",
    token_veified_successfully:"Valid token",
    token_expire:"This token has been expired",
    RESET_token_expired: "Reset link has expired. Please request a new password reset.",
    RESET_token_ALREADY_USED: "Reset link has already been used. Please request a new one.",
    google_register:"You are registered with google please log in with it",
    app_in_process_approve_by_admin:"Your application is in process, Please wait until Admin approved",
    app_reject:"Your application is rejected, Please contact admin",
    question_create:"Question created successfully",
    assesment_create:"Assesment created successfully",
    assesor_create:"Assesor created successfully",
    assessor_profile_not_create:"Assessor profile not able to create",
    take_exam:"Exam submitted successfully",
    not_take_exam:"Exam not submitted",
    candidate_create:"Candidate created successfully",
    assesment_not_create:"Assesment could'nt created Something went wrong",
    assesor_not_create:"Assesor could'nt created Something went wrong",
    candidate_not_create:"Candidate could'nt created Something went wrong",
    question_not_create:"Question could'nt created Something went wrong",
    question_not_found:"Question not found",
    question_delete:"Question data delete successfully",
    job_role_not_found:"Job Role not found",
    sub_scheme_not_found:"Sub Scheme not found",
    job_role_found:"Job Role List",
    sub_scheme_found:"Sub Scheme List",
    assesment_not_found:"Assesment not found",
    batch_not_found:"Batch not found",
    batch_found:"Batch List",
    assesment_found:"Assesment Question List",
    assessor_not_found:"Assessor not found.",
    assessor_found:"Assessor list.",
    assessor_list_delete:"Assessor list data delete successfully",
    candidate_found:"Candidate Report List",
    candidate_not_found:"Candidate Report not found",
    job_role_created:"Job Role created successfully",
    job_role_not_created:"Jobrole could'nt created Something went wrong",
    question_bank_found:"Question Bank list",
    question_bank_not_found:"Question Bank list not found",
    token_for_auth:"You need to provide token for authentication",
    user_not_exist:"The user does not exists on this platform",
    user_unauthorized_to_access:"You are not authorized to access this response",
    user_found:"User List",
    user_create:"User created successfully",
    user_not_create:"User could'nt created something went wrong",
    userlogin_list_delete:"User list data delete successfully",
    section_found:'section list',
    image_delete:'image deleted successfully',
    section_create:'section created successfully',
    section_not_found:'section not found',
    jobRole_not_found:'JobRole not found',
    section_list_delete:"Section list data delete successfully",
    subScheme_list_delete:"Sub-Scheme data delete successfully",
    job_role_list_delete:"JobRole list data delete successfully",
    status_change:'Status change successfully.',
    status_not_change:'Status not change.',
    status_same_exists:'request status are same as already existing status',
    image_not_found:'image not found',
    assessment_list_create:"Assessment list created successfully",
    assessment_list_not_create:"Assessment list not created",
    assesor_already_register:"Assessor details you have entered already registered",
    assesor_email_already_register:"Assessor email you have entered already registered",
    assesor_sip_already_register:"Assessor sip id you have entered already registered",
    pm_vishwakarma_env_missing:"PM Vishwakarma does not exist",
    userdemo_create:"User demo created successfully",
    userdemo_not_create:"User demo could'nt created something went wrong",
    session_expired:"Session has been expired",
    exam_center_already_exist:"Exam center already exists",
    exam_center_not_able_create:"Exam center not able to create",
    state_name_not_valid:"State name is not valid",
    exam_center_created_successfully_with_new_TP:"Exam center created successfully with new TP",
    exam_center_added_for_existing_TP: "Exam center added for existing TP",
    request_payload_invalid:"Request payload is required",
    INVALID_USERNAME_PASSWORD:"Invalid username or password.",
    exam_center_get_successfully:"Exam center list get successfully",
    exam_center_empty:"Exam center is empty",
    exam_center_not_found:"Exam center not found",
    req_status_same_already_exist:"Request status are same as already existing status",
    status_not_able_change:"Status not able to change",
    exam_center_status_changed:"Exam center status changed successfully",
    exam_center_removed_successfully:"Exam center removed successfully",
    exam_center_not_able_delete:"Exam center not able to delete",
    exam_center_id_required:"Exam center id is required",
    exam_center_not_able_update:"Exam center not able to update",
    exam_center_update_successfully:"Exam center updated successfully.",
    client_not_able_delete:"Client not able to delete.",
    district_get_successfully:"Districts get successfully.",
    district_not_able_get:"District not able to get.",
    otp_create:"OTP is sent to your Mobile Number.",
    op_dashboard:"Operation Dashboard Details.",
    content_dashboard:"Content Dashboard Details.",
    hr_dashboard:"Hr Dashboard Details.",
    otp_not_create:"OTP has not sent.",
    otp_verified:"Your mobile number is verified.",
    otp_not_verified:"OTP doesn't match.",
    file_not_received:"File Not Provided.",
    email_not_provided: "Email Not Provided.",
    client_creation_failed: "Client creation failed.",
    client_added_successfully: "Client added successfully.",
    image_upload_failed: "Image upload failed.",
    client_already_exist: "Client already exist.",
    wrong_file_type: "Wrong file type.",
    file_type_should_be: "Only accept .jpg, .jpeg, .png file.",
    nothing_provided_to_update: "No data provided to update.",
    client_details_available: "Client details available.",
    assessor_details_available: "Assessor details available.",
    no_client_found: "No client found.",
    no_client_id_provided: "No client id provided.",
    email_address_can_not_be_changed: "Email address can not be updated.",
    client_code_can_not_be_changed: "Client code can not be updated.",
    client_fount_but_no_logo_image: "Client found but no logo image.",
    no_client_id_provided: "No client id provided.",
    client_status_changed_successfully: "Client status changed successfully.",
    no_client_status_provided: "No client status provided.",
    client_code_already_available: "Client code already exist.",
    scheme_create:"Scheme created successfully.",
    scheme_not_found:"Scheme not found.",
    scheme_found:"Scheme list.",
    scheme_list_delete:"Scheme list data delete successfully.",
    scheme_exists:"Scheme already exists.",
    scheme_code_exists:"Scheme code already exists.",
    scheme_name_exists:"Scheme name already exists.",
    scheme_id_required:"schemeId  is required.",
    scheme_id_not_found:"schemeId not found.",
    scheme_not_update:"SchemeId not able to update.",
    scheme_update:"Scheme updated successfully.",
    userDemo_not_update:"UserId not able to update.",
    otp_not_send:"OTP not send.",
    all_client_has_been_added_successfully: "All the clients has been added successfully.",
    duplicate_email_in_database: "Duplicate email in the database.",
    duplicate_email_in_excel: "Duplicate email in excel.",
    clients_has_been_added_successfully: "Clients has been added successfully.",
    duplicate_client_code_in_excel : "Duplicate client code is in excel.", 
    duplicate_client_code_in_database: "Duplicate client code is in database.",
    email_or_client_code_is_already_exist: "Email or client code is already exist.",

    user_role_already_exist: "User role already exist.",
    user_role_successfully_created: "User role successfully created.",
    no_user_role_data_provided_for_user_role_creation: "No user role data provided for user role creation.",
    no_user_role_data_provided_for_user_role_updation: "No user role data provided for user role updation.",
    user_role_details: "All the User role details available.",
    no_user_id_provided:"No user id provided.",
    existed_user_role_details_available: "Existed user role details available.",
    user_role_updated_successfully: "User role updated sucsessfully.",
    feature_list:"Feature list.",
    no_user_role_found: "No user role found.",
    existing_userEmail_or_userName: 'Existing "Email Id" and "User Name".',
    successfully_created_new_user: "Successfully created new user.",
    got_users_successfully: "Got users successfully.",
    got_user_deatils_successfully: "Got user details successfully.",
    no_details_given_to_update: "No details given to update.",
    successfully_updated_the_user: "Successfully updated the user details.",
    user_deleted_successfully: "User deleted successfully.",
    wrong_user_id_provided: "Wrong user Id provided.",
    no_user_found: "No user found.",
    no_assessor_found: "No assessor found.",
    no_such_user_id_exist: "No such user id exist.",
    assessor_added_successfully: "Assessor added successfully.",
    assessor_profile_not_found:"Assessor profile not found.",
    assessor_profile_get:'Assessor profile get successfully.',
    assessment_history_get:'Assessment History Details fetched successfully',
    no_assessor_id_provided: "No assessor id provided.",
    assessor_not_able_delete:"Assessor not able to delete.",
    assessor_profile_delete:"Assessor profile delete successfully.",
    assessor_profile_update:"Assessor profile updated successfully.",
    assessor_details_available: "Assessor details available.",
    assessor_not_saved:"Assessor data not found",
    assessor_creation_failed: "SIP creation failed.",
    sip_added_successfully: "SIP added successfully.",
    email_not_received:"Email not provided.",
    assessor_file_not_found:'file not found',
    assessor_file_upload_failed: "File upload failed.",
    user_role_can_not_be_deleted: "User role can't be deleted as it is assigned to a user.",
    user_role_successfully_deleted: "User role successfully deleted.",
    no_user_status_provided: "No user status provided.",
    user_status_changed_successfully: "User status changed successfully.",
    can_not_insert_empty_file: "Can not insert empty file atleast one client should be there.",
    can_not_insert_empty_nos_file: "Can not insert empty file atleast one NOS should be there.",
    can_not_insert_empty_verification_file:"Can not insert empty file",
    nos_not_found:"Nos not found",
    nos_found:"Nos List",
    duplicate_nos_in_excel: "Duplicate nos in excel.",
    nos_is_already_exist: "Nos is already exist.",
    data_already_exists: "Data already exists in database.",
    all_nos_has_been_added_successfully: "All the nos has been added successfully.",
    nos_has_been_added_successfully: "Nos has been added successfully.",
    nosId_not_found:"nosId doesn't exists",
    nosId_not_update:"Nos theory detail not update",
    nosId_not_found:"nosId doesn't exists",
    nosId_found:"NOS found",
    nos_update:"NOS update successfully",
    nos_delete:"NOS data delete successfully",
    nos_not_able_delete:"NOS not able to delete.",
    question_form_already_register:"Question bank details you have entered already registered",
    question_form_not_create:"Question bank could'nt created Something went wrong",
    question_form_create:"Question bank created Successfully",
    question_bank_not_create:"Question bank not created",
    question_not_found:"Question bank details not found.",
    question_bank_found:"Question bank list.",
    question_bankId_not_found:"QuestionbankId doesn't exists",
    question_bank_not_update:"Questionbank details not update",
    question_bank_update:"Question bank update successfully",
    question_bank_delete:"Question bank data delete successfully",
    question_list_not_found:"Question details not found.",
    question_list_found:"Question list",
    question_options_added_successfully: "Options added successfully.",
    options_image_not_found:'Image not found',
    question_option_upload_failed: "File upload failed.",
    question_is_already_exist: "Question is already exist.",
    proctor_not_create:"Proctor could'nt created Something went wrong",
    proctor_already_register:"Proctor details you have entered already registered",
    proctor_added_successfully: "Proctor added successfully.",
    proctor_not_saved:"Proctor data not found",
    proctor_profile_not_found:"Proctor profile not found.",
    proctor_profile_get:'Proctor profile get successfully.',
    proctor_not_found:"Proctor not found.",
    proctor_found:"Proctor list.",
    proctor_details_available: "Proctor details available.",
    no_proctor_id_provided: "No proctor id provided.",
    proctor_not_able_delete:"Proctor not able to delete.",
    proctor_profile_delete:"Proctor profile delete successfully.",
    proctor_profile_update:"Proctor profile update successfully.",
    proctor_file_upload_failed: "File upload failed.",

    instruction_not_create:"Instruction could'nt created Something went wrong",
    instruction_already_register:"Instruction details you have entered already registered",
    instruction_create:"Instruction created Successfully",
    instruction_not_create:"Instruction not created",
    instruction_not_found:"Instruction not found.",
    instruction_found:"Instruction list.",
    instructionId_not_found:"InstructionId doesn't exists",
    instructionId_not_update:"Instruction detail not update",
    instruction_update:"Instruction update successfully",
    instruction_delete:"Instruction data delete successfully",
    instruction_not_able_delete:"Instruction not able to delete.",
    instruction_hindi_description:"On selected hindi language only hindi dsecription allow",
    instruction_english_description:"On selected english language only english dsecription allow",
    instruction_both_description:"On selected both language english and hindi dsecription allow",
    useremark_create:"User remark created successfully",
    userdemo_not_able_delete:"User not able to delete.",
    userdemo_delete:"User data delete successfully",

    user_role_not_provided: "UserRole not provided.",
    superAdmin_can_not_be_deleted: "Super Admin can not be deleted.",
    superAdmin_can_not_be_updated: "Super Admin can not be updated.",

    training_partner_not_provided: "Training partner not provided",
    existing_training_partner: "Existing training partner.",
    training_partner_added_successfully: "Training partner added successfully",
    issue_in_adding_training_partner: "Issue in adding training partner.",
    successfully_fetched_trainingPartner: "Successfully fetched training partner.",
    no_existing_training_partner_with_this_name: "No existing training parnter with this name.",
    no_exam_center_id_is_provided : "No exam center id is provided.",
    no_new_status_provided: "No new status provided",

    user_not_enabled: "Contact the administrator for login approval.",
    batch_not_active: "Contact the administrator.",
    logged_in_another_device : "Logged in another device.",
    asssessor_password_fetched_successfully: "Assessor password fetched successfully",
    already_password_provided: "Already password provided",

    dashboard_success: "Operation successful",
    dashboard_created: "Dashboard created successfully",
    dashboard_updated: "Dashboard updated successfully",
    dashboard_deleted: "Dashboard deleted successfully",
    dashboard_not_found: "Dashboard not found",
    dashboard_something_wrong: "Something went wrong",
    no_dashboard_found: "No dashboard found.",
    admin_approval_pending:"Admin approval pending",
    USER_ALREADY_LOGGEDOUT: "User already logged out",
    TOKEN_BLACKLISTED: "Token blacklisted",
    student_marks_absent:"If candidate is absent, enter 'ABSENT' for all marks",
    training_partner_created_successfully: "Training partner created successfully",
    training_partner_already_exist: "Training partner with this name, mobile number, or email already exists",

    // OTP Security Messages
    otp_locked:"OTP verification is locked due to multiple failed attempts",
    otp_unlocked:"OTP lockout has been successfully removed",
    otp_security_status_retrieved:"OTP security status retrieved successfully",
    otp_invalid_attempts_remaining:"Invalid OTP. {attempts} attempts remaining before OTP lockout",
    otp_lockout_expired:"OTP lockout has expired",
    invalid_credential:"Invalid credentials."
}

