
require("dotenv").config()

module.exports = {
    auth_failed:"Authentication Failed",
    something_wrong:"Something wrong",
    errorMessage :'Oops! Something went wrong here...',
    request_invalid:"Your request is not valid",
    mobile_num_invalid:"Mobile Number is not valid",
    mobile_num_exists:"Mobile No. already exists.",
    password_invalid:"Password must contain at least one letter, one number and one special character (!@#$%^&*)",
    enter_correct_password:"Please Enter correct Password",
    reset_password_link_sent_to_email:"Reset Password link sent to your registered Email",
    reset_password_success:"Reset password successfully",
    password_not_reset:"Password not able to reset",
    enter_old_password:"Please enter correct/valid old password",
    password_change_success:"Password Changed Successfully",
    new_password_not_same_as_old_password:"New Password must not be same as old password",
    pincode_invalid:"Pincode is not valid",
    org_not_found:"Organisation not found",
    org_list_not_found:"Organisation list not found",
    org_list_get:"Organisation list get successfully",
    email_not_verified:"Email is not verified, Please verify your email",
    email_not_register:"Email is not registered, Please register",
    user_login_success:"User login successfully",
    user_not_login:"User not able to login",
    sub_scheme_create:"Sub-Scheme created Successfully",
    subScheme_exist:"Sub-Scheme already exist",
    user_profile_create:"User Profile created Successfully",
    user_profile_not_create:"User Profile not able to create",
    user_profile_already_create:"User Profile already created",
    user_profile_get:"User Profile get Successfully",
    jobe_role_create:"Job Role Created Successfully",
    jobe_role_not_create:"Job Role not Created!",
    sub_scheme_not_create:"Sub-scheme not Created!",
    jobeRole_exist:"Job Role exist!",
    user_profile_update:"User Profile has been updated successfully",
    user_profile_not_created:"User profile is not created",
    create_user_profile:"Please create User profile",
    user_not_found:"User not found",
    user_not_active:"User is not in active state. Please contact admin",
    user_exist_already:"User already exists.",
    user_type_admin:"User type should be super admin",
    user_created:"User created Successfully",
    user_not_create:"User not able to create",
    user_role_invalid:"User Role is not valid",
    user_type_invalid:"User Type is not Valid",
    user_profile_list:'User profile list get successfully.',
    tour_viewed:"Tour successfully viewed",
    user_already_register:"User details you have entered already registered",
    client_profile_get:'Client profile get successfully',
    client_profile_create:"Client Profile created successfully",
    batch_create:"Batch created successfully",
    batch_assign:"Batch assign successfully",
    client_profile_update:"Client Profile updated successfully",
    client_profile_not_create:"Client profile not able to create",
    batch_not_create:"Batch not able to create",
    assignBatch_not_find:"Batch list not found",
    client_profile_not_found:"Client Profile not found",
    client_profile_delete:"Client profile data delete successfully",
    client_status_change:"client status changed successfully",
    client_profile_approved_by_admin:"User Profile approved by admin successfully",
    state_get:"States get successfully",
    city_get:"cities get successfully",
    country_name_required:"country name required",
    state_not_found:"State Name not found",
    state_fips_required:"State fips code is required",
    accept_terms_invalid:"Accept Terms and condition is not valid",
    verify_your_email:"Please verify your email address",
    email_already_verified:"Email is already verified",
    email_verified:"Congratulations! Your email has been successfully verified",
    email_verify_to_login:"Please verify Email to login",
    token_missed:"Token is missing",
    token_invalid:"Token is not Valid",
    token_required:"Token is required",
    token_expire:"This token has been expired",
    google_register:"You are registered with google please log in with it",
    app_in_process_approve_by_admin:"Your application is in process, Please wait until Admin approved",
    app_reject:"Your application is rejected, Please contact admin",
    question_create:"Question created successfully",
    assesment_create:"Assesment created successfully",
    assesor_create:"Assesor created successfully",
    assessor_profile_not_create:"Assessor profile not able to create",
    take_exam:"Exam submitted successfully",
    not_take_exam:"Exam not submitted",
    candidate_create:"Candidate created successfully",
    assesment_not_create:"Assesment could'nt created Something went wrong",
    assesor_not_create:"Assesor could'nt created Something went wrong",
    candidate_not_create:"Candidate could'nt created Something went wrong",
    question_not_create:"Question could'nt created Something went wrong",
    question_not_found:"Question not found",
    question_delete:"Question data delete successfully",
    job_role_not_found:"Job Role not found",
    sub_scheme_not_found:"Sub Scheme not found",
    job_role_found:"Job Role List",
    sub_scheme_found:"Sub Scheme List",
    assesment_not_found:"Assesment not found",
    batch_not_found:"Batch not found",
    batch_found:"Batch List",
    assesment_found:"Assesment Question List",
    assessor_not_found:"Assessor not found",
    assessor_found:"Assessor List",
    assessor_list_delete:"Assessor list data delete successfully",
    candidate_found:"Candidate Report List",
    candidate_not_found:"Candidate Report not found",
    job_role_created:"Job Role created successfully",
    job_role_not_created:"Jobrole could'nt created Something went wrong",
    question_bank_found:"Question Bank list",
    question_bank_not_found:"Question Bank list not found",
    question_bank_delete:"Question bank data delete successfully",
    token_for_auth:"You need to provide token for authentication",
    user_not_exist:"The user does not exists on this platform",
    user_unauthorized_to_access:"You are not authorized to access this response",
    user_found:"User List",
    user_create:"User created successfully",
    user_not_create:"User could'nt created something went wrong",
    userlogin_list_delete:"User list data delete successfully",
    section_found:'section list',
    image_delete:'image deleted successfully',
    section_create:'section created successfully',
    section_not_found:'section not found',
    jobRole_not_found:'JobRole not found',
    section_list_delete:"Section list data delete successfully",
    subScheme_list_delete:"Sub-Scheme data delete successfully",
    job_role_list_delete:"JobRole list data delete successfully",
    status_change:'Status change Successfully',
    status_not_change:'status not change',
    status_same_exists:'request status are same as already existing status',
    image_not_found:'image not found',
    assessment_list_create:"Assessment list created successfully",
    assessment_list_not_create:"Assessment list not created",
    assesor_already_register:"Assessor details you have entered already registered",
    userdemo_create:"User demo created successfully",
    userdemo_not_create:"User demo could'nt created something went wrong",
    session_expired:"Session has been expired",
    exam_center_already_exist:"Exam center already exists",
    exam_center_not_able_create:"Exam center not able to create",
    state_name_not_valid:"State name is not valid",
    exam_center_created_successfully:"Exam center created successfully",
    request_payload_invalid:"Request payload is required",
    exam_center_get_successfully:"Exam center list get successfully",
    exam_center_empty:"Exam center is empty",
    exam_center_not_found:"Exam center not found",
    req_status_same_already_exist:"Request status are same as already existing status",
    status_not_able_change:"Status not able to change",
    exam_center_status_changed:"Exam center status changed successfully",
    exam_center_removed_successfully:"Exam center removed successfully",
    exam_center_not_able_delete:"Exam center not able to delete",
    exam_center_id_required:"Exam center id is required",
    exam_center_not_able_update:"Exam center not able to update",
    exam_center_update_successfully:"Exam center updated successfully",
    client_not_able_delete:"Client not able to delete",
    district_get_successfully:"Districts get successfully",
    district_not_able_get:"District not able to get",
    otp_create:"OTP is sent to your Mobile Number",
    otp_not_create:"OTP has not sent",
    otp_verified:"Your mobile number is verified!",
    otp_not_verified:"OTP doesn't match",
    file_not_received:"File Not Provided",
    email_not_provided: "Email Not Provided",
    client_creation_failed: "client creation failed",
    client_added_successfully: "client added successfully",
    image_upload_failed: "image upload failed",
    client_already_exist: "Client already exist",
    wrong_file_type: "Wrong file type",
    file_type_should_be: "Only accept .jpg, .jpeg, .png file",
    nothing_provided_to_update: "No data provided to update",
    client_details_available: "client details available",
    no_client_found: "No client found",
    no_client_id_provided: "No client id provided",
    email_address_can_not_be_changed: "email address can not be updated",
    client_code_can_not_be_changed: "client code can not be updated",

    client_fount_but_no_logo_image: "client found but no logo image",
    no_client_id_provided: "no client id provided",
    client_status_changed_successfully: "client status changed successfully",
    no_client_status_provided: "no client status provided",
    client_code_already_available: "client code already available",

    scheme_create:"Scheme created successfully",
    scheme_not_found:"Scheme not found",
    scheme_found:"Scheme list",
    scheme_list_delete:"Scheme list data delete successfully",
    scheme_exists:"Scheme already exists.",
    scheme_id_required:"schemeId  is required",
    scheme_id_not_found:"schemeId not found",
    scheme_not_update:"SchemeId not able to update",
    scheme_update:"Scheme updated Successfully",
    userDemo_not_update:"UserId not able to update",
    otp_not_send:"OTP not send",



    all_client_has_been_added_successfully: "all the clients has been added successfully",
    duplicate_email_in_database: "duplicate email in the database",
    duplicate_email_in_excel: "duplicate email in excel",
    clients_has_been_added_successfully: "clients has been added successfully",
    USER_ALREADY_LOGGEDOUT: "User already logged out",
    TOKEN_BLACKLISTED: "Token blacklisted",
}